import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Runs before paint, synchronously, in <head> — this is what prevents a
// flash of the wrong theme on load. Reads localStorage first, falls back to
// system preference on first visit. Wrapped in try/catch since
// localStorage/matchMedia can throw in some privacy-mode/embedded contexts,
// and a broken theme script must never be the thing that breaks the page.
const themeInitScript = `
(function () {
  try {
    var stored = localStorage.getItem('theme');
    var theme = (stored === 'light' || stored === 'dark')
      ? stored
      : (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    document.documentElement.setAttribute('data-theme', theme);
  } catch (e) {}
})();
`;

export default function RootLayout({ children }) {
    return (
        // suppressHydrationWarning: the no-flash script above sets
        // data-theme on this element BEFORE React hydrates, on purpose —
        // that's what prevents a flash of the wrong theme, and it's the
        // whole reason the script exists. Server-rendered markup has no
        // data-theme attribute at all (the server doesn't know the
        // client's stored preference or system setting), so React's
        // hydration diff always sees a mismatch here. suppressHydrationWarning
        // only silences the warning for this element's own attributes —
        // it does not disable hydration mismatch detection anywhere else
        // in the tree, and does not change the no-flash behavior at all.
        <html lang="en" suppressHydrationWarning>
        <head>
            <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/* ✅ ClerkProvider MUST be inside <body> */}
        <ClerkProvider>
            {children}
        </ClerkProvider>
        </body>
        </html>
    );
}
